const { Client, GatewayIntentBits, EmbedBuilder } = require("discord.js");

const CONFIG = {
  DISCORD_TOKEN: process.env.DISCORD_TOKEN,
    NEWS_CHANNEL_ID: process.env.NEWS_CHANNEL_ID,
      RAPIDAPI_KEY: process.env.RAPIDAPI_KEY,

        // Add accounts: { handle, user_id }
          // To find user_id: search "get twitter user id by username" online
            WATCH_ACCOUNTS: [
                { handle: "HINDU_KlNG", user_id: "2038193116151209984" },
                    { handle: "OpenAI", user_id: "972651467338199041" },
                        { handle: "NASA", user_id: "11348282" },
                          ],

                            POLL_INTERVAL_MS: 60 * 1000, // 60 seconds (safe for free tier)
                            };

                            const discord = new Client({
                              intents: [GatewayIntentBits.Guilds, GatewayIntentBits.GuildMessages],
                              });

                              const seenIds = {};

                              async function fetchTweets(user_id) {
                                const url = `https://twitter-x.p.rapidapi.com/user/tweets?user_id=${user_id}&limit=10`;
                                  const res = await fetch(url, {
                                      method: "GET",
                                          headers: {
                                                "Content-Type": "application/json",
                                                      "x-rapidapi-host": "twitter-x.p.rapidapi.com",
                                                            "x-rapidapi-key": CONFIG.RAPIDAPI_KEY,
                                                                },
                                                                  });

                                                                    if (!res.ok) throw new Error(`HTTP ${res.status}`);
                                                                      const data = await res.json();

                                                                        // Extract tweets from response
                                                                          const entries =
                                                                              data?.data?.user?.result?.timeline_v2?.timeline?.instructions?.find(
                                                                                    (i) => i.type === "TimelineAddEntries"
                                                                                        )?.entries || [];

                                                                                          const tweets = entries
                                                                                              .filter((e) => e.content?.entryType === "TimelineTimelineItem")
                                                                                                  .map((e) => {
                                                                                                        const result = e.content?.itemContent?.tweet_results?.result;
                                                                                                              const legacy = result?.legacy;
                                                                                                                    if (!legacy) return null;
                                                                                                                          return {
                                                                                                                                  id: legacy.id_str,
                                                                                                                                          text: legacy.full_text,
                                                                                                                                                  created_at: legacy.created_at,
                                                                                                                                                          likes: legacy.favorite_count,
                                                                                                                                                                  retweets: legacy.retweet_count,
                                                                                                                                                                          replies: legacy.reply_count,
                                                                                                                                                                                  media: legacy.entities?.media?.[0]?.media_url_https || null,
                                                                                                                                                                                          is_retweet: legacy.full_text?.startsWith("RT @"),
                                                                                                                                                                                                };
                                                                                                                                                                                                    })
                                                                                                                                                                                                        .filter(Boolean);

                                                                                                                                                                                                          return tweets;
                                                                                                                                                                                                          }

                                                                                                                                                                                                          function buildEmbed(tweet, handle) {
                                                                                                                                                                                                            const tweetUrl = `https://x.com/${handle}/status/${tweet.id}`;

                                                                                                                                                                                                              const embed = new EmbedBuilder()
                                                                                                                                                                                                                  .setColor(0x000000)
                                                                                                                                                                                                                      .setAuthor({
                                                                                                                                                                                                                            name: `@${handle}`,
                                                                                                                                                                                                                                  url: `https://x.com/${handle}`,
                                                                                                                                                                                                                                      })
                                                                                                                                                                                                                                          .setDescription(tweet.text.length > 4096 ? tweet.text.slice(0, 4093) + "..." : tweet.text)
                                                                                                                                                                                                                                              .setURL(tweetUrl)
                                                                                                                                                                                                                                                  .setTimestamp(new Date(tweet.created_at))
                                                                                                                                                                                                                                                      .setFooter({ text: `𝕏 Post · @${handle}` })
                                                                                                                                                                                                                                                          .addFields({
                                                                                                                                                                                                                                                                name: "Engagement",
                                                                                                                                                                                                                                                                      value: `❤️ ${fmt(tweet.likes)}  🔁 ${fmt(tweet.retweets)}  💬 ${fmt(tweet.replies)}`,
                                                                                                                                                                                                                                                                          });

                                                                                                                                                                                                                                                                            if (tweet.media) embed.setImage(tweet.media);

                                                                                                                                                                                                                                                                              return embed;
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              function fmt(n) {
                                                                                                                                                                                                                                                                                if (!n) return "0";
                                                                                                                                                                                                                                                                                  if (n >= 1_000_000) return (n / 1_000_000).toFixed(1) + "M";
                                                                                                                                                                                                                                                                                    if (n >= 1_000) return (n / 1_000).toFixed(1) + "K";
                                                                                                                                                                                                                                                                                      return String(n);
                                                                                                                                                                                                                                                                                      }

                                                                                                                                                                                                                                                                                      async function fetchAndPost(channel, account) {
                                                                                                                                                                                                                                                                                        try {
                                                                                                                                                                                                                                                                                            const tweets = await fetchTweets(account.user_id);
                                                                                                                                                                                                                                                                                                if (!tweets || tweets.length === 0) return;

                                                                                                                                                                                                                                                                                                    // First run — seed seen IDs, don't post old tweets
                                                                                                                                                                                                                                                                                                        if (!seenIds[account.handle]) {
                                                                                                                                                                                                                                                                                                              seenIds[account.handle] = new Set(tweets.map((t) => t.id));
                                                                                                                                                                                                                                                                                                                    console.log(`[${account.handle}] Ready — ${seenIds[account.handle].size} existing tweets cached`);
                                                                                                                                                                                                                                                                                                                          return;
                                                                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                                                                                  const newTweets = tweets.filter((t) => !seenIds[account.handle].has(t.id));
                                                                                                                                                                                                                                                                                                                                      if (newTweets.length === 0) return;

                                                                                                                                                                                                                                                                                                                                          for (const tweet of [...newTweets].reverse()) {
                                                                                                                                                                                                                                                                                                                                                // Skip retweets if you want (remove this line to include them)
                                                                                                                                                                                                                                                                                                                                                      if (tweet.is_retweet) continue;

                                                                                                                                                                                                                                                                                                                                                            await channel.send({ embeds: [buildEmbed(tweet, account.handle)] });
                                                                                                                                                                                                                                                                                                                                                                  seenIds[account.handle].add(tweet.id);
                                                                                                                                                                                                                                                                                                                                                                        console.log(`[${new Date().toISOString()}] ✅ Posted @${account.handle}: ${tweet.text.slice(0, 50)}`);
                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                              } catch (err) {
                                                                                                                                                                                                                                                                                                                                                                                  console.error(`[${account.handle}] Error: ${err.message}`);
                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                    discord.once("clientReady", async () => {
                                                                                                                                                                                                                                                                                                                                                                                      console.log(`\n✅ Bot online: ${discord.user.tag}`);

                                                                                                                                                                                                                                                                                                                                                                                        const channel = await discord.channels.fetch(CONFIG.NEWS_CHANNEL_ID).catch(() => null);
                                                                                                                                                                                                                                                                                                                                                                                          if (!channel) {
                                                                                                                                                                                                                                                                                                                                                                                              console.error("❌ Channel not found — check NEWS_CHANNEL_ID");
                                                                                                                                                                                                                                                                                                                                                                                                  process.exit(1);
                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                      console.log(`📡 Watching: ${CONFIG.WATCH_ACCOUNTS.map((a) => "@" + a.handle).join(", ")}`);
                                                                                                                                                                                                                                                                                                                                                                                                        console.log(`⏱️  Polling every ${CONFIG.POLL_INTERVAL_MS / 1000}s\n`);

                                                                                                                                                                                                                                                                                                                                                                                                          // Seed on startup
                                                                                                                                                                                                                                                                                                                                                                                                            for (const account of CONFIG.WATCH_ACCOUNTS) {
                                                                                                                                                                                                                                                                                                                                                                                                                await fetchAndPost(channel, account);
                                                                                                                                                                                                                                                                                                                                                                                                                  }

                                                                                                                                                                                                                                                                                                                                                                                                                    // Poll forever
                                                                                                                                                                                                                                                                                                                                                                                                                      setInterval(async () => {
                                                                                                                                                                                                                                                                                                                                                                                                                          for (const account of CONFIG.WATCH_ACCOUNTS) {
                                                                                                                                                                                                                                                                                                                                                                                                                                await fetchAndPost(channel, account);
                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                      }, CONFIG.POLL_INTERVAL_MS);
                                                                                                                                                                                                                                                                                                                                                                                                                                      });

                                                                                                                                                                                                                                                                                                                                                                                                                                      discord.on("error", (err) => console.error("Discord error:", err));
                                                                                                                                                                                                                                                                                                                                                                                                                                      discord.login(CONFIG.DISCORD_TOKEN);