const fs = require("fs");
setTimeout(() => { process.exit(0); }, 4 * 60 * 1000);
const CONFIG = {
  DISCORD_WEBHOOK: process.env.DISCORD_WEBHOOK,
  WATCH_ACCOUNTS: ["elonmusk", "NASA", "NVIDIAGeForce", "Intel", "Google", "YouTube", "HINDU_KlNG"],
  SEEN_FILE: "seen_ids.json",
};
const ACCOUNT_META = { elonmusk: { name: "Elon Musk", color: 15658734, badge: "👤" }, NASA: { name: "NASA", color: 742801, badge: "🚀" }, NVIDIAGeForce: { name: "NVIDIA GeForce", color: 7774464, badge: "🎮" }, Intel: { name: "Intel", color: 29125, badge: "💻" }, Google: { name: "Google", color: 4359668, badge: "🔍" }, YouTube: { name: "YouTube", color: 16711680, badge: "▶️" }, HINDU_KlNG: { name: "HINDU KlNG", color: 16737280, badge: "👑" } };
function loadSeen() { try { if (fs.existsSync(CONFIG.SEEN_FILE)) return JSON.parse(fs.readFileSync(CONFIG.SEEN_FILE, "utf8")); } catch (e) {} return {}; }
function saveSeen(seen) { fs.writeFileSync(CONFIG.SEEN_FILE, JSON.stringify(seen, null, 2)); }
async function sleep(ms) { return new Promise(r => setTimeout(r, ms)); }
async function sendWebhook(embed) { const res = await fetch(CONFIG.DISCORD_WEBHOOK, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ embeds: [embed] }), signal: AbortSignal.timeout(10000) }); if (!res.ok) throw new Error(`Webhook ${res.status}: ${await res.text()}`); }
async function fetchTweets(handle) { const urls = [`https://xcancel.com/${handle}/rss`, `https://nitter.poast.org/${handle}/rss`, `https://twiiit.com/${handle}/rss`]; for (const url of urls) { try { const r = await fetch(url, { headers: { "User-Agent": "Mozilla/5.0" }, signal: AbortSignal.timeout(8000) }); if (!r.ok) continue; const xml = await r.text(); const items = []; const matches = xml.matchAll(/<item>([\s\S]*?)<\/item>/g); for (const m of matches) { const i = m[1]; const title = i.match(/<title><!\[CDATA\[(.*?)\]\]><\/title>/)?.[1] || ""; const link = i.match(/<link>(.*?)<\/link>/)?.[1] || ""; const pub = i.match(/<pubDate>(.*?)<\/pubDate>/)?.[1] || ""; const desc = i.match(/<description><!\[CDATA\[(.*?)\]\]><\/description>/)?.[1] || ""; const id = link.match(/status\/(\d+)/)?.[1]; if (!id) continue; const img = desc.match(/<img[^>]+src="([^"]+)"/)?.[1]; items.push({ id, text: title.replace(/^R to @\w+: /,"").replace(/^RT by @\w+: /,"").replace(/&amp;/g,"&").trim(), link: `https://x.com/${handle}/status/${id}`, date: pub ? new Date(pub).toISOString() : new Date().toISOString(), image: img && img.startsWith("http") ? img : null, isRetweet: title.startsWith("RT by"), isReply: title.startsWith("R to") }); } if (items.length > 0) { console.log(`[${handle}] Got ${items.length} from ${url}`); return items; } } catch(e) { console.log(`[${handle}] ${url} failed: ${e.message}`); } } return []; }
function buildEmbed(tweet, handle) { const meta = ACCOUNT_META[handle] || { name: handle, color: 1316135, badge: "📢" }; let type, icon, color; if (tweet.isRetweet) { type="Repost"; icon="🔁"; color=52307; } else if (tweet.isReply) { type="Reply"; icon="💬"; color=1940463; } else if (tweet.image) { type="Photo"; icon="🖼️"; color=16740096; } else { type="Post"; icon="✍️"; color=meta.color; } const date = new Date(tweet.date); const df = date.toLocaleDateString("en-US",{weekday:"long",year:"numeric",month:"long",day:"numeric",hour:"2-digit",minute:"2-digit",timeZone:"UTC",timeZoneName:"short"}); const e = { color, author: { name: `${meta.badge}  ${meta.name}  ·  @${handle}`, url: `https://x.com/${handle}`, icon_url: `https://unavatar.io/twitter/${handle}` }, title: `${icon}  New ${type} from @${handle}`, url: tweet.link, description: tweet.text.length > 0 ? tweet.text.slice(0,4096) : "*Media only post*", fields: [{ name:"━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━", value:`🕐  **${df}**`, inline:false },{ name:"🔗  View Post", value:`**[→ Open on X](${tweet.link})**`, inline:true },{ name:"👤  Profile", value:`**[→ @${handle}](https://x.com/${handle})**`, inline:true }], timestamp: date.toISOString(), footer: { text:"N.I.F. Private News Service  ·  𝕏 Twitter/X", icon_url:"https://abs.twimg.com/favicons/twitter.3.ico" } }; if (tweet.image) e.image = { url: tweet.image }; return e; }
async function main() { console.log("🤖 Bot starting..."); try { await sendWebhook({ color: 0x00c853, title: "🤖 N.I.F. News Bot Online", description: "Checking for new posts...", timestamp: new Date().toISOString(), footer: { text: "N.I.F. Private News Service" } }); console.log("✅ Webhook works!"); } catch(err) { console.error(`❌ Webhook failed: ${err.message}`); process.exit(1); } const seen = loadSeen(); let total = 0; for (const handle of CONFIG.WATCH_ACCOUNTS) { const tweets = await fetchTweets(handle); if (!tweets.length) { await sleep(500); continue; } if (!seen[handle]) { seen[handle] = tweets.map(t=>t.id); console.log(`[${handle}] Seeded ${seen[handle].length}`); await sleep(500); continue; } const set = new Set(seen[handle]); const fresh = tweets.filter(t=>!set.has(t.id)); if (!fresh.length) { console.log(`[${handle}] No new posts`); } else { for (const t of [...fresh].reverse()) { try { await sendWebhook(buildEmbed(t, handle)); seen[handle].unshift(t.id); total++; console.log(`[${handle}] ✅ ${t.text.slice(0,60)}`); await sleep(500); } catch(e) { console.error(`[${handle}] ${e.message}`); } } seen[handle] = seen[handle].slice(0,50); } await sleep(500); } saveSeen(seen); console.log(`✅ Done! Posted ${total} new posts.`); process.exit(0); }
main();
